// flow-typed signature: 3ed389c8fbe6bde7cf2a8978d96a6678
// flow-typed version: <<STUB>>/babel-plugin-extensible-destructuring_v^4.0.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-extensible-destructuring'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-extensible-destructuring' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-extensible-destructuring/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-extensible-destructuring/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-extensible-destructuring/lib/index'>;
}
