// flow-typed signature: 0338d4fc8cd882ed630b4ad54747c866
// flow-typed version: <<STUB>>/extensible-runtime_v^4.0.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'extensible-runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'extensible-runtime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'extensible-runtime/lib/runtime' {
  declare module.exports: any;
}

// Filename aliases
declare module 'extensible-runtime/lib/runtime.js' {
  declare module.exports: $Exports<'extensible-runtime/lib/runtime'>;
}
