// flow-typed signature: 79c1d257b79df777051880328dbc9b88
// flow-typed version: <<STUB>>/glam-props_v^1.3.2/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'glam-props'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'glam-props' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'glam-props/__test__/bindStyles.spec' {
  declare module.exports: any;
}

declare module 'glam-props/__test__/useGlamProps.spec' {
  declare module.exports: any;
}

declare module 'glam-props/lib/bindStyles' {
  declare module.exports: any;
}

declare module 'glam-props/lib/index' {
  declare module.exports: any;
}

declare module 'glam-props/lib/useGlamProps' {
  declare module.exports: any;
}

declare module 'glam-props/src/bindStyles' {
  declare module.exports: any;
}

declare module 'glam-props/src/index' {
  declare module.exports: any;
}

declare module 'glam-props/src/useGlamProps' {
  declare module.exports: any;
}

// Filename aliases
declare module 'glam-props/__test__/bindStyles.spec.js' {
  declare module.exports: $Exports<'glam-props/__test__/bindStyles.spec'>;
}
declare module 'glam-props/__test__/useGlamProps.spec.js' {
  declare module.exports: $Exports<'glam-props/__test__/useGlamProps.spec'>;
}
declare module 'glam-props/lib/bindStyles.js' {
  declare module.exports: $Exports<'glam-props/lib/bindStyles'>;
}
declare module 'glam-props/lib/index.js' {
  declare module.exports: $Exports<'glam-props/lib/index'>;
}
declare module 'glam-props/lib/useGlamProps.js' {
  declare module.exports: $Exports<'glam-props/lib/useGlamProps'>;
}
declare module 'glam-props/src/bindStyles.js' {
  declare module.exports: $Exports<'glam-props/src/bindStyles'>;
}
declare module 'glam-props/src/index.js' {
  declare module.exports: $Exports<'glam-props/src/index'>;
}
declare module 'glam-props/src/useGlamProps.js' {
  declare module.exports: $Exports<'glam-props/src/useGlamProps'>;
}
