// flow-typed signature: 5c280052847930f64e46b05882c96425
// flow-typed version: <<STUB>>/react-native-facebook-login_v^1.5.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-facebook-login'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-facebook-login' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-facebook-login/example/components/facebook/FBLoginMock' {
  declare module.exports: any;
}

declare module 'react-native-facebook-login/example/components/Login' {
  declare module.exports: any;
}

declare module 'react-native-facebook-login/example/components/LoginMock' {
  declare module.exports: any;
}

declare module 'react-native-facebook-login/example/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-facebook-login/index.android' {
  declare module.exports: any;
}

declare module 'react-native-facebook-login/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-facebook-login/lib/services' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-facebook-login/example/components/facebook/FBLoginMock.js' {
  declare module.exports: $Exports<'react-native-facebook-login/example/components/facebook/FBLoginMock'>;
}
declare module 'react-native-facebook-login/example/components/Login.js' {
  declare module.exports: $Exports<'react-native-facebook-login/example/components/Login'>;
}
declare module 'react-native-facebook-login/example/components/LoginMock.js' {
  declare module.exports: $Exports<'react-native-facebook-login/example/components/LoginMock'>;
}
declare module 'react-native-facebook-login/example/index.ios.js' {
  declare module.exports: $Exports<'react-native-facebook-login/example/index.ios'>;
}
declare module 'react-native-facebook-login/index.android.js' {
  declare module.exports: $Exports<'react-native-facebook-login/index.android'>;
}
declare module 'react-native-facebook-login/index.ios.js' {
  declare module.exports: $Exports<'react-native-facebook-login/index.ios'>;
}
declare module 'react-native-facebook-login/lib/services.js' {
  declare module.exports: $Exports<'react-native-facebook-login/lib/services'>;
}
