// flow-typed signature: 77d9864537b67bc6447879fc3a0c8ce2
// flow-typed version: <<STUB>>/react-native-modalbox_vlatest/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-modalbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-modalbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-modalbox/Example2/index.android' {
  declare module.exports: any;
}

declare module 'react-native-modalbox/Example2/index.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-modalbox/Example2/index.android.js' {
  declare module.exports: $Exports<'react-native-modalbox/Example2/index.android'>;
}
declare module 'react-native-modalbox/Example2/index.ios.js' {
  declare module.exports: $Exports<'react-native-modalbox/Example2/index.ios'>;
}
declare module 'react-native-modalbox/index' {
  declare module.exports: $Exports<'react-native-modalbox'>;
}
declare module 'react-native-modalbox/index.js' {
  declare module.exports: $Exports<'react-native-modalbox'>;
}
