// flow-typed signature: 03530e7520b1592be2031ddf064ea169
// flow-typed version: <<STUB>>/react-native-extended-stylesheet_v^0.3.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-extended-stylesheet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-extended-stylesheet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-extended-stylesheet/examples/media-queries/app' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/examples/media-queries/component' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/examples/readme/app' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/examples/readme/component' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/examples/rem/app' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/examples/rem/component' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/examples/simple/app' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/examples/simple/component' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/examples/themes-dynamic/app' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/examples/themes-dynamic/component' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/examples/themes-dynamic/dark' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/examples/themes-dynamic/light' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/examples/themes-dynamic/themes' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/examples/themes-static/app' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/examples/themes-static/component' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/examples/themes-static/dark' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/examples/themes-static/light' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/__mocks__/react-native' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/__tests__/api.test' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/__tests__/child.test' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/__tests__/memoize.test' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/__tests__/sheet.test' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/__tests__/style.test' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/__tests__/utils.test' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/__tests__/value.test' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/api' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/child' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/index' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/memoize' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/replacers/__tests__/media-queries.test' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/replacers/__tests__/operation.test' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/replacers/__tests__/percent.test' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/replacers/__tests__/rem.test' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/replacers/__tests__/scale.test' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/replacers/__tests__/vars.test' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/replacers/media-queries' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/replacers/operation' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/replacers/percent' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/replacers/rem' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/replacers/scale' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/replacers/vars' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/sheet' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/style' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/utils' {
  declare module.exports: any;
}

declare module 'react-native-extended-stylesheet/src/value' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-extended-stylesheet/examples/media-queries/app.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/examples/media-queries/app'>;
}
declare module 'react-native-extended-stylesheet/examples/media-queries/component.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/examples/media-queries/component'>;
}
declare module 'react-native-extended-stylesheet/examples/readme/app.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/examples/readme/app'>;
}
declare module 'react-native-extended-stylesheet/examples/readme/component.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/examples/readme/component'>;
}
declare module 'react-native-extended-stylesheet/examples/rem/app.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/examples/rem/app'>;
}
declare module 'react-native-extended-stylesheet/examples/rem/component.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/examples/rem/component'>;
}
declare module 'react-native-extended-stylesheet/examples/simple/app.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/examples/simple/app'>;
}
declare module 'react-native-extended-stylesheet/examples/simple/component.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/examples/simple/component'>;
}
declare module 'react-native-extended-stylesheet/examples/themes-dynamic/app.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/examples/themes-dynamic/app'>;
}
declare module 'react-native-extended-stylesheet/examples/themes-dynamic/component.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/examples/themes-dynamic/component'>;
}
declare module 'react-native-extended-stylesheet/examples/themes-dynamic/dark.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/examples/themes-dynamic/dark'>;
}
declare module 'react-native-extended-stylesheet/examples/themes-dynamic/light.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/examples/themes-dynamic/light'>;
}
declare module 'react-native-extended-stylesheet/examples/themes-dynamic/themes.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/examples/themes-dynamic/themes'>;
}
declare module 'react-native-extended-stylesheet/examples/themes-static/app.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/examples/themes-static/app'>;
}
declare module 'react-native-extended-stylesheet/examples/themes-static/component.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/examples/themes-static/component'>;
}
declare module 'react-native-extended-stylesheet/examples/themes-static/dark.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/examples/themes-static/dark'>;
}
declare module 'react-native-extended-stylesheet/examples/themes-static/light.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/examples/themes-static/light'>;
}
declare module 'react-native-extended-stylesheet/src/__mocks__/react-native.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/__mocks__/react-native'>;
}
declare module 'react-native-extended-stylesheet/src/__tests__/api.test.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/__tests__/api.test'>;
}
declare module 'react-native-extended-stylesheet/src/__tests__/child.test.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/__tests__/child.test'>;
}
declare module 'react-native-extended-stylesheet/src/__tests__/memoize.test.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/__tests__/memoize.test'>;
}
declare module 'react-native-extended-stylesheet/src/__tests__/sheet.test.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/__tests__/sheet.test'>;
}
declare module 'react-native-extended-stylesheet/src/__tests__/style.test.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/__tests__/style.test'>;
}
declare module 'react-native-extended-stylesheet/src/__tests__/utils.test.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/__tests__/utils.test'>;
}
declare module 'react-native-extended-stylesheet/src/__tests__/value.test.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/__tests__/value.test'>;
}
declare module 'react-native-extended-stylesheet/src/api.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/api'>;
}
declare module 'react-native-extended-stylesheet/src/child.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/child'>;
}
declare module 'react-native-extended-stylesheet/src/index.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/index'>;
}
declare module 'react-native-extended-stylesheet/src/memoize.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/memoize'>;
}
declare module 'react-native-extended-stylesheet/src/replacers/__tests__/media-queries.test.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/replacers/__tests__/media-queries.test'>;
}
declare module 'react-native-extended-stylesheet/src/replacers/__tests__/operation.test.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/replacers/__tests__/operation.test'>;
}
declare module 'react-native-extended-stylesheet/src/replacers/__tests__/percent.test.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/replacers/__tests__/percent.test'>;
}
declare module 'react-native-extended-stylesheet/src/replacers/__tests__/rem.test.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/replacers/__tests__/rem.test'>;
}
declare module 'react-native-extended-stylesheet/src/replacers/__tests__/scale.test.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/replacers/__tests__/scale.test'>;
}
declare module 'react-native-extended-stylesheet/src/replacers/__tests__/vars.test.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/replacers/__tests__/vars.test'>;
}
declare module 'react-native-extended-stylesheet/src/replacers/media-queries.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/replacers/media-queries'>;
}
declare module 'react-native-extended-stylesheet/src/replacers/operation.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/replacers/operation'>;
}
declare module 'react-native-extended-stylesheet/src/replacers/percent.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/replacers/percent'>;
}
declare module 'react-native-extended-stylesheet/src/replacers/rem.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/replacers/rem'>;
}
declare module 'react-native-extended-stylesheet/src/replacers/scale.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/replacers/scale'>;
}
declare module 'react-native-extended-stylesheet/src/replacers/vars.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/replacers/vars'>;
}
declare module 'react-native-extended-stylesheet/src/sheet.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/sheet'>;
}
declare module 'react-native-extended-stylesheet/src/style.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/style'>;
}
declare module 'react-native-extended-stylesheet/src/utils.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/utils'>;
}
declare module 'react-native-extended-stylesheet/src/value.js' {
  declare module.exports: $Exports<'react-native-extended-stylesheet/src/value'>;
}
