// flow-typed signature: 34fb931be09fc31317f1259a0fef8e99
// flow-typed version: <<STUB>>/react-native-fcm_v^6.2.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-fcm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-fcm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-fcm/index' {
  declare module.exports: $Exports<'react-native-fcm'>;
}
declare module 'react-native-fcm/index.js' {
  declare module.exports: $Exports<'react-native-fcm'>;
}
