// flow-typed signature: a9203e6e68c460250f340732b9f277e2
// flow-typed version: <<STUB>>/react-native-htmlview_v^0.5.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-htmlview'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-htmlview' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-htmlview/__mocks__/react-native' {
  declare module.exports: any;
}

declare module 'react-native-htmlview/__mocks__/View' {
  declare module.exports: any;
}

declare module 'react-native-htmlview/htmlToElement' {
  declare module.exports: any;
}

declare module 'react-native-htmlview/HTMLView' {
  declare module.exports: any;
}

declare module 'react-native-htmlview/vendor/entities' {
  declare module.exports: any;
}

declare module 'react-native-htmlview/vendor/htmlparser2' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-htmlview/__mocks__/react-native.js' {
  declare module.exports: $Exports<'react-native-htmlview/__mocks__/react-native'>;
}
declare module 'react-native-htmlview/__mocks__/View.js' {
  declare module.exports: $Exports<'react-native-htmlview/__mocks__/View'>;
}
declare module 'react-native-htmlview/htmlToElement.js' {
  declare module.exports: $Exports<'react-native-htmlview/htmlToElement'>;
}
declare module 'react-native-htmlview/HTMLView.js' {
  declare module.exports: $Exports<'react-native-htmlview/HTMLView'>;
}
declare module 'react-native-htmlview/index' {
  declare module.exports: $Exports<'react-native-htmlview'>;
}
declare module 'react-native-htmlview/index.js' {
  declare module.exports: $Exports<'react-native-htmlview'>;
}
declare module 'react-native-htmlview/vendor/entities.js' {
  declare module.exports: $Exports<'react-native-htmlview/vendor/entities'>;
}
declare module 'react-native-htmlview/vendor/htmlparser2.js' {
  declare module.exports: $Exports<'react-native-htmlview/vendor/htmlparser2'>;
}
