// flow-typed signature: 81b629a68f59de588d4f297f63de7428
// flow-typed version: <<STUB>>/react-native-sqlite-storage_v^3.2.2/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-sqlite-storage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-sqlite-storage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-sqlite-storage/lib/sqlite.core' {
  declare module.exports: any;
}

declare module 'react-native-sqlite-storage/scripts/rnpm-postlink' {
  declare module.exports: any;
}

declare module 'react-native-sqlite-storage/sqlite' {
  declare module.exports: any;
}

declare module 'react-native-sqlite-storage/test/index.ios.callback' {
  declare module.exports: any;
}

declare module 'react-native-sqlite-storage/test/index.ios.promise' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-sqlite-storage/lib/sqlite.core.js' {
  declare module.exports: $Exports<'react-native-sqlite-storage/lib/sqlite.core'>;
}
declare module 'react-native-sqlite-storage/scripts/rnpm-postlink.js' {
  declare module.exports: $Exports<'react-native-sqlite-storage/scripts/rnpm-postlink'>;
}
declare module 'react-native-sqlite-storage/sqlite.js' {
  declare module.exports: $Exports<'react-native-sqlite-storage/sqlite'>;
}
declare module 'react-native-sqlite-storage/test/index.ios.callback.js' {
  declare module.exports: $Exports<'react-native-sqlite-storage/test/index.ios.callback'>;
}
declare module 'react-native-sqlite-storage/test/index.ios.promise.js' {
  declare module.exports: $Exports<'react-native-sqlite-storage/test/index.ios.promise'>;
}
