// flow-typed signature: 69a0fc0337b0c83e024f2403488a292a
// flow-typed version: <<STUB>>/react-native-google-sign-in_v^0.0.14/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-google-sign-in'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-google-sign-in' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-google-sign-in/js/GoogleSignIn.android' {
  declare module.exports: any;
}

declare module 'react-native-google-sign-in/js/GoogleSignIn.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-google-sign-in/index' {
  declare module.exports: $Exports<'react-native-google-sign-in'>;
}
declare module 'react-native-google-sign-in/index.js' {
  declare module.exports: $Exports<'react-native-google-sign-in'>;
}
declare module 'react-native-google-sign-in/js/GoogleSignIn.android.js' {
  declare module.exports: $Exports<'react-native-google-sign-in/js/GoogleSignIn.android'>;
}
declare module 'react-native-google-sign-in/js/GoogleSignIn.ios.js' {
  declare module.exports: $Exports<'react-native-google-sign-in/js/GoogleSignIn.ios'>;
}
