// flow-typed signature: 6462f1821635d1a605571d2d8d9248cc
// flow-typed version: <<STUB>>/styled-props_v^0.2.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-props'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-props' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-props/__test__/bind.spec' {
  declare module.exports: any;
}

declare module 'styled-props/__test__/styledProps.spec' {
  declare module.exports: any;
}

declare module 'styled-props/lib/bind' {
  declare module.exports: any;
}

declare module 'styled-props/lib/index' {
  declare module.exports: any;
}

declare module 'styled-props/lib/styledProps' {
  declare module.exports: any;
}

declare module 'styled-props/src/bind' {
  declare module.exports: any;
}

declare module 'styled-props/src/index' {
  declare module.exports: any;
}

declare module 'styled-props/src/styledProps' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-props/__test__/bind.spec.js' {
  declare module.exports: $Exports<'styled-props/__test__/bind.spec'>;
}
declare module 'styled-props/__test__/styledProps.spec.js' {
  declare module.exports: $Exports<'styled-props/__test__/styledProps.spec'>;
}
declare module 'styled-props/lib/bind.js' {
  declare module.exports: $Exports<'styled-props/lib/bind'>;
}
declare module 'styled-props/lib/index.js' {
  declare module.exports: $Exports<'styled-props/lib/index'>;
}
declare module 'styled-props/lib/styledProps.js' {
  declare module.exports: $Exports<'styled-props/lib/styledProps'>;
}
declare module 'styled-props/src/bind.js' {
  declare module.exports: $Exports<'styled-props/src/bind'>;
}
declare module 'styled-props/src/index.js' {
  declare module.exports: $Exports<'styled-props/src/index'>;
}
declare module 'styled-props/src/styledProps.js' {
  declare module.exports: $Exports<'styled-props/src/styledProps'>;
}
