export globalVariables from './globalVariables'
export combineStyles from './combineStyles'
export truncate from './truncate'
export HTMLView from './react-native-htmlview'
export database from './database'
export verseToStrong from './verseToStrong'
